# Generated by Django 2.1.15 on 2020-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
