# Generated by Django 2.1.15 on 2020-06-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200617_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_genre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
