# Generated by Django 2.1.15 on 2020-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='media/ghost.jpeg', upload_to=''),
        ),
    ]
