# Generated by Django 2.1.15 on 2020-05-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200511_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='ghost.jpeg', upload_to=''),
        ),
    ]
