# Generated by Django 2.1.15 on 2020-05-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200512_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('category',)},
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default='/media/ghost.jpeg', upload_to=''),
        ),
    ]
