# Generated by Django 2.1.15 on 2020-10-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='origin_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
