# Generated by Django 2.1.15 on 2020-10-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201021_0606'),
        ('projects', '0003_auto_20201020_2246'),
    ]

    operations = [
    ]
